services:
  lexer-svc:
    build:
      context: .
      dockerfile: Dockerfile
      args: { ENTRY: "lexer:app", PORT: 8000 }
    command: uvicorn lexer:app --host 0.0.0.0 --port 8000
    ports: ["8001:8000"]

  parser-svc:
    build:
      context: .
      dockerfile: Dockerfile
      args: { ENTRY: "parser:app", PORT: 8000 }
    command: uvicorn parser:app --host 0.0.0.0 --port 8000
    environment:
      CODEGEN_URL: http://codegen-svc:8000
    ports: ["8002:8000"]

  codegen-svc:
    build:
      context: .
      dockerfile: Dockerfile
      args: { ENTRY: "codegen:app", PORT: 8000 }
    command: uvicorn codegen:app --host 0.0.0.0 --port 8000
    ports: ["8003:8000"]

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args: { ENTRY: "orchestrator:app", PORT: 8000 }
    command: uvicorn orchestrator:app --host 0.0.0.0 --port 8000
    environment:
      LEX_URL:  http://lexer-svc:8000/lex
      PARSE_URL: http://parser-svc:8000/compile
    depends_on: [lexer-svc, parser-svc, codegen-svc]
    ports: ["8080:8000"]
